## http://localhost:8080/
server : 
  port : 8080
  
spring :
  datasource :
    #url :   jdbc:oracle:thin:@localhost:1521/XE
    url : jdbc:log4jdbc:oracle:thin:@localhost:1521/XE
    username : testUser
    password : 1234
    #driver-class-name : oracle.jdbc.OracleDriver
    driver-class-name : net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  thymeleaf: # Thymeleaf (1. 루트폴더 변경, 2. 타임리프 캐시 설정 변경)
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    mode: HTML
    cache: false # default true, 개발 시에는 false로 두는 것이 좋음
  output : 
      ansi : 
        enabled : always
  profiles : 
    active : local # 프로필 설정
  devtools:
    livereload:
      enabled: true





# Mybatis mapper 위치 설정
mybatis : 
  mapper-locations : classpath*:mapper/**/*.xml

logging :
  level :
      org :
        springframework : debug
        web : debug
      root : info
      com : 
        bank : 
          banklist : info
          controller : debug

